package br.com.byron.gamefinder.utils;

import java.util.HashMap;
import java.util.Map;

public class TagUtils {

    public static Map<Integer, String> getTagList() {
        final Map<Integer, String> tagIdToName = new HashMap<>();
        tagIdToName.put(492, "Indie");
        tagIdToName.put(19, "Action");
        tagIdToName.put(21, "Adventure");
        tagIdToName.put(597, "Casual");
        tagIdToName.put(122, "RPG");
        tagIdToName.put(599, "Simulation");
        tagIdToName.put(9, "Strategy");
        tagIdToName.put(4182, "Singleplayer");
        tagIdToName.put(493, "Early Access");
        tagIdToName.put(113, "Free to Play");
        tagIdToName.put(3871, "2D");
        tagIdToName.put(4191, "3D");
        tagIdToName.put(4166, "Atmospheric");
        tagIdToName.put(1684, "Fantasy");
        tagIdToName.put(1742, "Story Rich");
        tagIdToName.put(4305, "Colorful");
        tagIdToName.put(3859, "Multiplayer");
        tagIdToName.put(1664, "Puzzle");
        tagIdToName.put(3964, "Pixel Graphics");
        tagIdToName.put(3834, "Exploration");
        tagIdToName.put(128, "Massively Multiplayer");
        tagIdToName.put(701, "Sports");
        tagIdToName.put(4726, "Cute");
        tagIdToName.put(4667, "Violent");
        tagIdToName.put(3839, "First-Person");
        tagIdToName.put(3993, "Combat");
        tagIdToName.put(699, "Racing");
        tagIdToName.put(4085, "Anime");
        tagIdToName.put(12095, "Sexual Content");
        tagIdToName.put(6650, "Nudity");
        tagIdToName.put(4106, "Action-Adventure");
        tagIdToName.put(1773, "Arcade");
        tagIdToName.put(4136, "Funny");
        tagIdToName.put(3942, "Sci-fi");
        tagIdToName.put(1774, "Shooter");
        tagIdToName.put(1654, "Relaxing");
        tagIdToName.put(4345, "Gore");
        tagIdToName.put(1667, "Horror");
        tagIdToName.put(4004, "Retro");
        tagIdToName.put(5350, "Family Friendly");
        tagIdToName.put(1697, "Third Person");
        tagIdToName.put(7481, "Controller");
        tagIdToName.put(7208, "Female Protagonist");
        tagIdToName.put(4252, "Stylized");
        tagIdToName.put(1695, "Open World");
        tagIdToName.put(1625, "Platformer");
        tagIdToName.put(1685, "Co-op");
        tagIdToName.put(1662, "Survival");
        tagIdToName.put(1775, "PvP");
        tagIdToName.put(6426, "Choices Matter");
        tagIdToName.put(4791, "Top-Down");
        tagIdToName.put(4175, "Realistic");
        tagIdToName.put(1719, "Comedy");
        tagIdToName.put(6730, "PvE");
        tagIdToName.put(3799, "Visual Novel");
        tagIdToName.put(4342, "Dark");
        tagIdToName.put(4747, "Character Customization");
        tagIdToName.put(3968, "Physics");
        tagIdToName.put(4195, "Cartoony");
        tagIdToName.put(5716, "Mystery");
        tagIdToName.put(7250, "Linear");
        tagIdToName.put(1663, "FPS");
        tagIdToName.put(3916, "Old School");
        tagIdToName.put(6971, "Multiple Endings");
        tagIdToName.put(5379, "2D Platformer");
        tagIdToName.put(3843, "Online Co-Op");
        tagIdToName.put(4026, "Difficult");
        tagIdToName.put(1721, "Psychological Horror");
        tagIdToName.put(21978, "VR");
        tagIdToName.put(4057, "Magic");
        tagIdToName.put(4172, "Medieval");
        tagIdToName.put(3810, "Sandbox");
        tagIdToName.put(1708, "Tactical");
        tagIdToName.put(1756, "Great Soundtrack");
        tagIdToName.put(4231, "Action RPG");
        tagIdToName.put(4295, "Futuristic");
        tagIdToName.put(4094, "Minimalist");
        tagIdToName.put(1755, "Space");
        tagIdToName.put(1643, "Building");
        tagIdToName.put(6815, "Hand-drawn");
        tagIdToName.put(1698, "Point & Click");
        tagIdToName.put(1702, "Crafting");
        tagIdToName.put(12472, "Management");
        tagIdToName.put(4255, "Shoot 'Em Up");
        tagIdToName.put(1716, "Roguelike");
        tagIdToName.put(5984, "Drama");
        tagIdToName.put(4562, "Cartoon");
        tagIdToName.put(7368, "Local Multiplayer");
        tagIdToName.put(84, "Design & Illustration");
        tagIdToName.put(3959, "Roguelite");
        tagIdToName.put(3798, "Side Scroller");
        tagIdToName.put(8945, "Resource Management");
        tagIdToName.put(5125, "Procedural Generation");
        tagIdToName.put(4604, "Dark Fantasy");
        tagIdToName.put(6129, "Logic");
        tagIdToName.put(5395, "3D Platformer");
        tagIdToName.put(5611, "Mature");
        tagIdToName.put(3978, "Survival Horror");
        tagIdToName.put(4486, "Choose Your Own Adventure");
        tagIdToName.put(1036, "Education");
        tagIdToName.put(5537, "Puzzle Platformer");
        tagIdToName.put(4947, "Romance");
        tagIdToName.put(4325, "Turn-Based Combat");
        tagIdToName.put(5608, "Emotional");
        tagIdToName.put(7743, "1980s");
        tagIdToName.put(87, "Utilities");
        tagIdToName.put(1646, "Hack and Slash");
        tagIdToName.put(1741, "Turn-Based Strategy");
        tagIdToName.put(9204, "Immersive Sim");
        tagIdToName.put(1678, "War");
        tagIdToName.put(11014, "Interactive Fiction");
        tagIdToName.put(14139, "Turn-Based Tactics");
        tagIdToName.put(17389, "Tabletop");
        tagIdToName.put(9130, "Hentai");
        tagIdToName.put(30358, "Nature");
        tagIdToName.put(3835, "Post-apocalyptic");
        tagIdToName.put(7332, "Base Building");
        tagIdToName.put(1659, "Zombies");
        tagIdToName.put(9551, "Dating Sim");
        tagIdToName.put(42804, "Action Roguelike");
        tagIdToName.put(1738, "Hidden Object");
        tagIdToName.put(6691, "1990's");
        tagIdToName.put(1710, "Surreal");
        tagIdToName.put(4434, "JRPG");
        tagIdToName.put(4885, "Bullet Hell");
        tagIdToName.put(3841, "Local Co-Op");
        tagIdToName.put(1720, "Dungeon Crawler");
        tagIdToName.put(3987, "Historical");
        tagIdToName.put(10695, "Party-Based RPG");
        tagIdToName.put(1687, "Stealth");
        tagIdToName.put(4711, "Replay Value");
        tagIdToName.put(5094, "Narration");
        tagIdToName.put(5900, "Walking Simulator");
        tagIdToName.put(5154, "Score Attack");
        tagIdToName.put(1677, "Turn-Based");
        tagIdToName.put(24904, "NSFW");
        tagIdToName.put(4168, "Military");
        tagIdToName.put(4145, "Cinematic");
        tagIdToName.put(31275, "Text-Based");
        tagIdToName.put(3814, "Third-Person Shooter");
        tagIdToName.put(15172, "Conversation");
        tagIdToName.put(4637, "Top-Down Shooter");
        tagIdToName.put(44868, "LGBTQ+");
        tagIdToName.put(4975, "2.5D");
        tagIdToName.put(1673, "Aliens");
        tagIdToName.put(4115, "Cyberpunk");
        tagIdToName.put(1038, "Web Publishing");
        tagIdToName.put(8369, "Investigation");
        tagIdToName.put(10397, "Memes");
        tagIdToName.put(5851, "Isometric");
        tagIdToName.put(5752, "Robots");
        tagIdToName.put(5711, "Team-Based");
        tagIdToName.put(5923, "Dark Humor");
        tagIdToName.put(6869, "Nonlinear");
        tagIdToName.put(6276, "Inventory Management");
        tagIdToName.put(1666, "Card Game");
        tagIdToName.put(3854, "Lore-Rich");
        tagIdToName.put(10235, "Life Sim");
        tagIdToName.put(1676, "RTS");
        tagIdToName.put(7926, "Artificial Intelligence");
        tagIdToName.put(12057, "Tutorial");
        tagIdToName.put(9541, "Demons");
        tagIdToName.put(17305, "Strategy RPG");
        tagIdToName.put(379975, "Clicker");
        tagIdToName.put(5186, "Psychological");
        tagIdToName.put(4400, "Abstract");
        tagIdToName.put(4064, "Thriller");
        tagIdToName.put(1759, "Perma Death");
        tagIdToName.put(5547, "Arena Shooter");
        tagIdToName.put(4695, "Economy");
        tagIdToName.put(3813, "Real Time Tactics");
        tagIdToName.put(5613, "Detective");
        tagIdToName.put(1734, "Fast-Paced");
        tagIdToName.put(10808, "Supernatural");
        tagIdToName.put(1644, "Driving");
        tagIdToName.put(1770, "Board Game");
        tagIdToName.put(5673, "Modern");
        tagIdToName.put(4234, "Short");
        tagIdToName.put(872, "Animation & Modeling");
        tagIdToName.put(5030, "Dystopian ");
        tagIdToName.put(3877, "Precision Platformer");
        tagIdToName.put(8013, "Software");
        tagIdToName.put(16689, "Time Management");
        tagIdToName.put(1714, "Psychedelic");
        tagIdToName.put(4840, "4 Player Local");
        tagIdToName.put(1645, "Tower Defense");
        tagIdToName.put(4236, "Loot");
        tagIdToName.put(21725, "Tactical RPG");
        tagIdToName.put(15045, "Flight");
        tagIdToName.put(4328, "City Builder");
        tagIdToName.put(29482, "Souls-like");
        tagIdToName.put(1693, "Classic");
        tagIdToName.put(1751, "Comic Book");
        tagIdToName.put(4684, "Wargame");
        tagIdToName.put(1621, "Music");
        tagIdToName.put(4158, "Beat 'em up");
        tagIdToName.put(4598, "Alternate History");
        tagIdToName.put(1628, "Metroidvania");
        tagIdToName.put(7948, "Soundtrack");
        tagIdToName.put(5577, "RPGMaker");
        tagIdToName.put(5363, "Destruction");
        tagIdToName.put(1669, "Moddable");
        tagIdToName.put(4700, "Movie");
        tagIdToName.put(16094, "Mythology");
        tagIdToName.put(8122, "Level Editor");
        tagIdToName.put(1743, "Fighting");
        tagIdToName.put(5652, "Collectathon");
        tagIdToName.put(8666, "Runner");
        tagIdToName.put(13906, "Game Development");
        tagIdToName.put(13782, "Experimental");
        tagIdToName.put(5411, "Beautiful");
        tagIdToName.put(7569, "Grid-Based Movement");
        tagIdToName.put(4036, "Parkour");
        tagIdToName.put(6378, "Crime");
        tagIdToName.put(4736, "2D Fighter");
        tagIdToName.put(32322, "Deckbuilding");
        tagIdToName.put(615955, "Idler");
        tagIdToName.put(4474, "CRPG");
        tagIdToName.put(784, "Video Production");
        tagIdToName.put(4155, "Class-Based");
        tagIdToName.put(1027, "Audio Production");
        tagIdToName.put(3878, "Competitive");
        tagIdToName.put(1754, "MMORPG");
        tagIdToName.put(19995, "Dark Comedy");
        tagIdToName.put(15277, "Philosophical");
        tagIdToName.put(5765, "Gun Customization");
        tagIdToName.put(791774, "Card Battler");
        tagIdToName.put(4758, "Twin Stick Shooter");
        tagIdToName.put(5794, "Science");
        tagIdToName.put(1100687, "Automobile Sim");
        tagIdToName.put(4150, "World War II");
        tagIdToName.put(4508, "Co-op Campaign");
        tagIdToName.put(17894, "Cats");
        tagIdToName.put(11104, "Vehicular Combat");
        tagIdToName.put(1752, "Rhythm");
        tagIdToName.put(4608, "Swordplay");
        tagIdToName.put(6506, "3D Fighter");
        tagIdToName.put(4364, "Grand Strategy");
        tagIdToName.put(16598, "Space Sim");
        tagIdToName.put(4046, "Dragons");
        tagIdToName.put(176981, "Battle Royale");
        tagIdToName.put(7432, "Lovecraftian");
        tagIdToName.put(5055, "eSports");
        tagIdToName.put(4835, "6DOF");
        tagIdToName.put(4845, "Capitalism");
        tagIdToName.put(255534, "Automation");
        tagIdToName.put(13190, "America");
        tagIdToName.put(29363, "3D Vision");
        tagIdToName.put(5372, "Conspiracy");
        tagIdToName.put(10816, "Split Screen");
        tagIdToName.put(6052, "Noir");
        tagIdToName.put(1665, "Match 3");
        tagIdToName.put(916648, "Creature Collector");
        tagIdToName.put(4878, "Parody ");
        tagIdToName.put(1445, "Software Training");
        tagIdToName.put(5796, "Bullet Time");
        tagIdToName.put(5228, "Blood");
        tagIdToName.put(220585, "Colony Sim");
        tagIdToName.put(87918, "Farming Sim");
        tagIdToName.put(4559, "Quick-Time Events");
        tagIdToName.put(4202, "Trading");
        tagIdToName.put(1651, "Satire");
        tagIdToName.put(3955, "Character Action Game");
        tagIdToName.put(198631, "Mystery Dungeon");
        tagIdToName.put(620519, "Hero Shooter");
        tagIdToName.put(6625, "Time Manipulation");
        tagIdToName.put(9592, "Dynamic Narration");
        tagIdToName.put(353880, "Looter Shooter");
        tagIdToName.put(3952, "Gothic");
        tagIdToName.put(1100689, "Open World Survival Craft");
        tagIdToName.put(22602, "Agriculture");
        tagIdToName.put(24003, "Word Game");
        tagIdToName.put(21006, "Underground");
        tagIdToName.put(3920, "Cooking");
        tagIdToName.put(4853, "Political");
        tagIdToName.put(1732, "Voxel");
        tagIdToName.put(1777, "Steampunk");
        tagIdToName.put(4190, "Addictive");
        tagIdToName.put(4777, "Spectacle fighter");
        tagIdToName.put(5981, "Mining");
        tagIdToName.put(4821, "Mechs");
        tagIdToName.put(6915, "Martial Arts");
        tagIdToName.put(10679, "Time Travel");
        tagIdToName.put(7478, "Illuminati");
        tagIdToName.put(4102, "Combat Racing");
        tagIdToName.put(9564, "Hunting");
        tagIdToName.put(31579, "Otome");
        tagIdToName.put(1638, "Dog");
        tagIdToName.put(13070, "Solitaire");
        tagIdToName.put(1681, "Pirates");
        tagIdToName.put(1718, "MOBA");
        tagIdToName.put(17770, "Asynchronous Multiplayer");
        tagIdToName.put(13276, "Tanks");
        tagIdToName.put(5300, "God Game");
        tagIdToName.put(4018, "Vampire");
        tagIdToName.put(1084988, "Auto Battler");
        tagIdToName.put(1688, "Ninja");
        tagIdToName.put(3934, "Immersive");
        tagIdToName.put(1717, "Hex Grid");
        tagIdToName.put(15564, "Fishing");
        tagIdToName.put(5502, "Hacking");
        tagIdToName.put(9271, "Trading Card Game");
        tagIdToName.put(809, "Photo Editing");
        tagIdToName.put(5708, "Remake");
        tagIdToName.put(11123, "Mouse only");
        tagIdToName.put(4754, "Politics");
        tagIdToName.put(18594, "FMV");
        tagIdToName.put(7702, "Narrative");
        tagIdToName.put(1723, "Action RTS");
        tagIdToName.put(4376, "Assassin");
        tagIdToName.put(9157, "Underwater");
        tagIdToName.put(4161, "Real-Time");
        tagIdToName.put(1671, "Superhero");
        tagIdToName.put(4242, "Episodic");
        tagIdToName.put(1670, "4X");
        tagIdToName.put(5179, "Cold War");
        tagIdToName.put(7782, "Cult Classic");
        tagIdToName.put(180368, "Faith");
        tagIdToName.put(3965, "Epic");
        tagIdToName.put(5160, "Dinosaurs");
        tagIdToName.put(5432, "Programming");
        tagIdToName.put(1730, "Sokoban");
        tagIdToName.put(26921, "Political Sim");
        tagIdToName.put(1647, "Western");
        tagIdToName.put(1680, "Heist");
        tagIdToName.put(10383, "Transportation");
        tagIdToName.put(7178, "Party Game");
        tagIdToName.put(7108, "Party");
        tagIdToName.put(6310, "Diplomacy");
        tagIdToName.put(6910, "Naval");
        tagIdToName.put(1616, "Trains");
        tagIdToName.put(13382, "Archery");
        tagIdToName.put(51306, "Foreign");
        tagIdToName.put(8093, "Minigames");
        tagIdToName.put(16250, "Gambling");
        tagIdToName.put(9803, "Snow");
        tagIdToName.put(7107, "Real-Time with Pause");
        tagIdToName.put(4994, "Naval Combat");
        tagIdToName.put(97376, "Cozy");
        tagIdToName.put(4137, "Transhumanism");
        tagIdToName.put(552282, "Wholesome");
        tagIdToName.put(1674, "Typing");
        tagIdToName.put(769306, "Escape Room");
        tagIdToName.put(13577, "Sailing");
        tagIdToName.put(1091588, "Roguelike Deckbuilder");
        tagIdToName.put(14153, "Dungeons & Dragons");
        tagIdToName.put(11333, "Villain Protagonist");
        tagIdToName.put(5230, "Sequel");
        tagIdToName.put(7423, "Sniper");
        tagIdToName.put(5153, "Kickstarter");
        tagIdToName.put(8253, "Music-Based Procedural Generation");
        tagIdToName.put(56690, "On-Rails Shooter");
        tagIdToName.put(14720, "Nostalgia");
        tagIdToName.put(5348, "Mod");
        tagIdToName.put(454187, "Traditional Roguelike");
        tagIdToName.put(17015, "Werewolves");
        tagIdToName.put(6702, "Mars");
        tagIdToName.put(7622, "Offroad");
        tagIdToName.put(1254546, "Football (Soccer)");
        tagIdToName.put(5390, "Time Attack");
        tagIdToName.put(9994, "Experience");
        tagIdToName.put(10437, "Trivia");
        tagIdToName.put(25085, "Touch-Friendly");
        tagIdToName.put(5382, "World War I");
        tagIdToName.put(6041, "Horses");
        tagIdToName.put(776177, "360 Video");
        tagIdToName.put(1649, "GameMaker");
        tagIdToName.put(4520, "Farming");
        tagIdToName.put(12190, "Boxing");
        tagIdToName.put(5310, "Games Workshop");
        tagIdToName.put(150626, "Gaming");
        tagIdToName.put(92092, "Jet");
        tagIdToName.put(4184, "Chess");
        tagIdToName.put(1100686, "Outbreak Sim");
        tagIdToName.put(15339, "Documentary");
        tagIdToName.put(4291, "Spaceships");
        tagIdToName.put(15954, "Silent Protagonist");
        tagIdToName.put(1733, "Unforgiving");
        tagIdToName.put(198913, "Motorbike");
        tagIdToName.put(1100688, "Medical Sim");
        tagIdToName.put(7038, "Golf");
        tagIdToName.put(71389, "Spelling");
        tagIdToName.put(856791, "Asymmetric VR");
        tagIdToName.put(1736, "LEGO");
        tagIdToName.put(6948, "Rome");
        tagIdToName.put(123332, "Bikes");
        tagIdToName.put(61357, "Electronic Music");
        tagIdToName.put(922563, "Roguevania");
        tagIdToName.put(19780, "Submarine");
        tagIdToName.put(1746, "Basketball");
        tagIdToName.put(7113, "Crowdfunded");
        tagIdToName.put(29855, "Ambient");
        tagIdToName.put(1254552, "Football (American)");
        tagIdToName.put(6621, "Pinball");
        tagIdToName.put(745697, "Social Deduction");
        tagIdToName.put(189941, "Instrumental Music");
        tagIdToName.put(22955, "Mini Golf");
        tagIdToName.put(8075, "TrackIR");
        tagIdToName.put(12286, "Warhammer 40K");
        tagIdToName.put(1753, "Skateboarding");
        tagIdToName.put(47827, "Wrestling");
        tagIdToName.put(337964, "Rock Music");
        tagIdToName.put(42089, "Jump Scare");
        tagIdToName.put(11634, "Vikings");
        tagIdToName.put(17927, "Pool");
        tagIdToName.put(3796, "Based On A Novel");
        tagIdToName.put(5727, "Baseball");
        tagIdToName.put(19568, "Cycling");
        tagIdToName.put(96359, "Skating");
        tagIdToName.put(5914, "Tennis");
        tagIdToName.put(14906, "Intentionally Awkward Controls");
        tagIdToName.put(15868, "Motocross");
        tagIdToName.put(11095, "Boss Rush");
        tagIdToName.put(117648, "8-bit Music");
        tagIdToName.put(7328, "Bowling");
        tagIdToName.put(176733, "Tile-Matching");
        tagIdToName.put(17337, "Lemmings");
        tagIdToName.put(35079, "Job Simulator");
        tagIdToName.put(324176, "Hockey");
        tagIdToName.put(348922, "Steam Machine");
        tagIdToName.put(8461, "Well-Written");
        tagIdToName.put(603297, "Hardware");
        tagIdToName.put(5407, "Benchmark");
        tagIdToName.put(252854, "BMX");
        tagIdToName.put(28444, "Snowboarding");
        tagIdToName.put(129761, "ATV");
        tagIdToName.put(7309, "Skiing");
        tagIdToName.put(33572, "Mahjong");
        tagIdToName.put(143739, "Electronic");
        tagIdToName.put(27758, "Voice Control");
        tagIdToName.put(323922, "Musou");
        tagIdToName.put(233824, "Feature Film");
        tagIdToName.put(1199779, "Extraction Shooter");
        tagIdToName.put(91114, "Shop Keeper");
        tagIdToName.put(6214, "Birds");
        tagIdToName.put(30927, "Fox");
        tagIdToName.put(49213, "Rugby");
        tagIdToName.put(847164, "Volleyball");
        tagIdToName.put(42329, "Coding");
        tagIdToName.put(5941, "Reboot");
        tagIdToName.put(1220528, "Hobby Sim");
        tagIdToName.put(158638, "Cricket");
        tagIdToName.put(363767, "Snooker");
        return tagIdToName;
    }

}
